backend:
  name: github
  repo: Clanbulance/belgium-final-connect-55157-87773-04-40571  # replace with your GH repo
  branch: gh-pages                         # branch where content lives
  auth_type: implicit    
  app_id: Ov23lijp0qYqmmWmfXnY    # GitHub OAuth App Client ID


media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "translations"
    label: "Translations"
    files:
      - file: "src/content/translations.en.json"
        label: "English"
        name: "en"
        fields:
          - { label: "Navigation Services", name: "nav_services", widget: "string" }
          - { label: "Navigation Pricing", name: "nav_pricing", widget: "string" }
          - { label: "Navigation Partnership", name: "nav_partnership", widget: "string" }
          - { label: "Navigation Contact", name: "nav_contact", widget: "string" }
          - { label: "Navigation CTA", name: "nav_cta", widget: "string" }
          - { label: "Navigation Subtitle", name: "nav_subtitle", widget: "string" }
          - { label: "Hero Badge", name: "hero_badge", widget: "string" }
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Title Gradient", name: "hero_title_gradient", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }
          - { label: "Hero CTA Primary", name: "hero_cta_primary", widget: "string" }
          - { label: "Hero CTA Secondary", name: "hero_cta_secondary", widget: "string" }
          - { label: "Hero Note", name: "hero_note", widget: "string" }
      - file: "src/content/translations.nl.json"
        label: "Dutch"
        name: "nl"
        fields:
          - { label: "Navigation Services", name: "nav_services", widget: "string" }
          - { label: "Navigation Pricing", name: "nav_pricing", widget: "string" }
          - { label: "Navigation Partnership", name: "nav_partnership", widget: "string" }
          - { label: "Navigation Contact", name: "nav_contact", widget: "string" }
          - { label: "Navigation CTA", name: "nav_cta", widget: "string" }
          - { label: "Navigation Subtitle", name: "nav_subtitle", widget: "string" }
          - { label: "Hero Badge", name: "hero_badge", widget: "string" }
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Title Gradient", name: "hero_title_gradient", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }
          - { label: "Hero CTA Primary", name: "hero_cta_primary", widget: "string" }
          - { label: "Hero CTA Secondary", name: "hero_cta_secondary", widget: "string" }
          - { label: "Hero Note", name: "hero_note", widget: "string" }

  - name: "services"
    label: "Services"
    files:
      - file: "src/content/services.en.json"
        label: "Services EN"
        name: "services_en"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "desc", widget: "text" }
              - { label: "Outcome", name: "outcome", widget: "string" }
      - file: "src/content/services.nl.json"
        label: "Services NL"
        name: "services_nl"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "desc", widget: "text" }
              - { label: "Outcome", name: "outcome", widget: "string" }

  - name: "pricing"
    label: "Pricing Packages"
    files:
      - file: "src/content/pricing.en.json"
        label: "Pricing EN"
        name: "pricing_en"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - label: "Packages"
            name: "packages"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Delivery", name: "delivery", widget: "string" }
              - { label: "Description", name: "desc", widget: "text" }
              - { label: "Popular", name: "popular", widget: "boolean", default: false }
              - label: "Features"
                name: "features"
                widget: "list"
                field: { label: "Feature", name: "feature", widget: "string" }
              - { label: "CTA Label", name: "cta", widget: "string" }
      - file: "src/content/pricing.nl.json"
        label: "Pricing NL"
        name: "pricing_nl"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - label: "Packages"
            name: "packages"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Delivery", name: "delivery", widget: "string" }
              - { label: "Description", name: "desc", widget: "text" }
              - { label: "Popular", name: "popular", widget: "boolean", default: false }
              - label: "Features"
                name: "features"
                widget: "list"
                field: { label: "Feature", name: "feature", widget: "string" }
              - { label: "CTA Label", name: "cta", widget: "string" }

  - name: "testimonials"
    label: "Testimonials"
    folder: "src/content/testimonials"
    create: true
    extension: "md"
    fields:
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Quote", name: "body", widget: "text" }

  - name: "cases"
    label: "Case Studies"
    folder: "src/content/cases"
    create: true
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Problem", name: "problem", widget: "text" }
      - { label: "Solution", name: "solution", widget: "text" }
      - { label: "Results", name: "results", widget: "text" }
      - { label: "KPIs", name: "kpis", widget: "list", field: { label: "KPI", name: "kpi", widget: "string" } }
      - { label: "Quote", name: "quote", widget: "string" }


publish_mode: editorial_workflow