export default {
  name: 'contact',
  title: 'Contact Section',
  type: 'document',
  fields: [
    {
      name: 'nl',
      title: '🇳🇱 Dutch (Nederlands)',
      type: 'object',
      fields: [
        { name: 'title', type: 'string', title: 'Title' },
        { name: 'subtitle', type: 'text', title: 'Subtitle' },
        { name: 'form_name', type: 'string', title: 'Form Name Label' },
        { name: 'form_email', type: 'string', title: 'Form Email Label' },
        { name: 'form_company', type: 'string', title: 'Form Company Label' },
        { name: 'form_message', type: 'string', title: 'Form Message Label' },
        { name: 'form_placeholder_name', type: 'string', title: 'Placeholder Name' },
        { name: 'form_placeholder_email', type: 'string', title: 'Placeholder Email' },
        { name: 'form_placeholder_company', type: 'string', title: 'Placeholder Company' },
        { name: 'form_placeholder_message', type: 'text', title: 'Placeholder Message' },
        { name: 'form_cta', type: 'string', title: 'Form CTA Button' },
        { name: 'email_title', type: 'string', title: 'Email Title' },
        { name: 'email_response', type: 'string', title: 'Email Response Time' },
        { name: 'location_title', type: 'string', title: 'Location Title' },
        { name: 'location_city', type: 'string', title: 'Location City' },
        { name: 'location_serving', type: 'string', title: 'Location Serving' },
        { name: 'consult_title', type: 'string', title: 'Consultation Title' },
        { name: 'consult_schedule', type: 'string', title: 'Consultation Schedule' },
        { name: 'consult_cta', type: 'string', title: 'Consultation CTA' },
        { name: 'hours_title', type: 'string', title: 'Office Hours Title' },
        { name: 'hours_weekday', type: 'string', title: 'Weekday Hours' },
        { name: 'hours_saturday', type: 'string', title: 'Saturday Hours' },
        { name: 'hours_sunday', type: 'string', title: 'Sunday Hours' },
      ],
    },
    {
      name: 'en',
      title: '🇬🇧 English',
      type: 'object',
      fields: [
        { name: 'title', type: 'string', title: 'Title' },
        { name: 'subtitle', type: 'text', title: 'Subtitle' },
        { name: 'form_name', type: 'string', title: 'Form Name Label' },
        { name: 'form_email', type: 'string', title: 'Form Email Label' },
        { name: 'form_company', type: 'string', title: 'Form Company Label' },
        { name: 'form_message', type: 'string', title: 'Form Message Label' },
        { name: 'form_placeholder_name', type: 'string', title: 'Placeholder Name' },
        { name: 'form_placeholder_email', type: 'string', title: 'Placeholder Email' },
        { name: 'form_placeholder_company', type: 'string', title: 'Placeholder Company' },
        { name: 'form_placeholder_message', type: 'text', title: 'Placeholder Message' },
        { name: 'form_cta', type: 'string', title: 'Form CTA Button' },
        { name: 'email_title', type: 'string', title: 'Email Title' },
        { name: 'email_response', type: 'string', title: 'Email Response Time' },
        { name: 'location_title', type: 'string', title: 'Location Title' },
        { name: 'location_city', type: 'string', title: 'Location City' },
        { name: 'location_serving', type: 'string', title: 'Location Serving' },
        { name: 'consult_title', type: 'string', title: 'Consultation Title' },
        { name: 'consult_schedule', type: 'string', title: 'Consultation Schedule' },
        { name: 'consult_cta', type: 'string', title: 'Consultation CTA' },
        { name: 'hours_title', type: 'string', title: 'Office Hours Title' },
        { name: 'hours_weekday', type: 'string', title: 'Weekday Hours' },
        { name: 'hours_saturday', type: 'string', title: 'Saturday Hours' },
        { name: 'hours_sunday', type: 'string', title: 'Sunday Hours' },
      ],
    },
  ],
};
