export default {
  name: 'footer',
  title: 'Footer Section',
  type: 'document',
  fields: [
    {
      name: 'nl',
      title: '🇳🇱 Dutch (Nederlands)',
      type: 'object',
      fields: [
        { name: 'desc', type: 'text', title: 'Description' },
        { name: 'collab', type: 'string', title: 'Collaboration Text' },
        { name: 'services_title', type: 'string', title: 'Services Title' },
        { name: 'services_1', type: 'string', title: 'Service 1' },
        { name: 'services_2', type: 'string', title: 'Service 2' },
        { name: 'services_3', type: 'string', title: 'Service 3' },
        { name: 'services_4', type: 'string', title: 'Service 4' },
        { name: 'company_title', type: 'string', title: 'Company Title' },
        { name: 'company_1', type: 'string', title: 'Company Link 1' },
        { name: 'company_2', type: 'string', title: 'Company Link 2' },
        { name: 'company_3', type: 'string', title: 'Company Link 3' },
        { name: 'company_4', type: 'string', title: 'Company Link 4' },
        { name: 'copyright', type: 'string', title: 'Copyright' },
        { name: 'privacy', type: 'string', title: 'Privacy Policy' },
        { name: 'terms', type: 'string', title: 'Terms of Service' },
      ],
    },
    {
      name: 'en',
      title: '🇬🇧 English',
      type: 'object',
      fields: [
        { name: 'desc', type: 'text', title: 'Description' },
        { name: 'collab', type: 'string', title: 'Collaboration Text' },
        { name: 'services_title', type: 'string', title: 'Services Title' },
        { name: 'services_1', type: 'string', title: 'Service 1' },
        { name: 'services_2', type: 'string', title: 'Service 2' },
        { name: 'services_3', type: 'string', title: 'Service 3' },
        { name: 'services_4', type: 'string', title: 'Service 4' },
        { name: 'company_title', type: 'string', title: 'Company Title' },
        { name: 'company_1', type: 'string', title: 'Company Link 1' },
        { name: 'company_2', type: 'string', title: 'Company Link 2' },
        { name: 'company_3', type: 'string', title: 'Company Link 3' },
        { name: 'company_4', type: 'string', title: 'Company Link 4' },
        { name: 'copyright', type: 'string', title: 'Copyright' },
        { name: 'privacy', type: 'string', title: 'Privacy Policy' },
        { name: 'terms', type: 'string', title: 'Terms of Service' },
      ],
    },
  ],
};
