export default {
  name: 'hero',
  title: 'Hero Section',
  type: 'document',
  fields: [
    {
      name: 'nl',
      title: '🇳🇱 Dutch (Nederlands)',
      type: 'object',
      fields: [
        { name: 'badge', type: 'string', title: 'Badge' },
        { name: 'title', type: 'string', title: 'Title' },
        { name: 'title_gradient', type: 'string', title: 'Title Gradient' },
        { name: 'subtitle', type: 'text', title: 'Subtitle' },
        { name: 'value1_title', type: 'string', title: 'Value 1 Title' },
        { name: 'value1_desc', type: 'string', title: 'Value 1 Description' },
        { name: 'value2_title', type: 'string', title: 'Value 2 Title' },
        { name: 'value2_desc', type: 'string', title: 'Value 2 Description' },
        { name: 'value3_title', type: 'string', title: 'Value 3 Title' },
        { name: 'value3_desc', type: 'string', title: 'Value 3 Description' },
        { name: 'value4_title', type: 'string', title: 'Value 4 Title' },
        { name: 'value4_desc', type: 'string', title: 'Value 4 Description' },
        { name: 'cta_primary', type: 'string', title: 'Primary CTA' },
        { name: 'cta_secondary', type: 'string', title: 'Secondary CTA' },
        { name: 'note', type: 'string', title: 'Note' },
      ],
    },
    {
      name: 'en',
      title: '🇬🇧 English',
      type: 'object',
      fields: [
        { name: 'badge', type: 'string', title: 'Badge' },
        { name: 'title', type: 'string', title: 'Title' },
        { name: 'title_gradient', type: 'string', title: 'Title Gradient' },
        { name: 'subtitle', type: 'text', title: 'Subtitle' },
        { name: 'value1_title', type: 'string', title: 'Value 1 Title' },
        { name: 'value1_desc', type: 'string', title: 'Value 1 Description' },
        { name: 'value2_title', type: 'string', title: 'Value 2 Title' },
        { name: 'value2_desc', type: 'string', title: 'Value 2 Description' },
        { name: 'value3_title', type: 'string', title: 'Value 3 Title' },
        { name: 'value3_desc', type: 'string', title: 'Value 3 Description' },
        { name: 'value4_title', type: 'string', title: 'Value 4 Title' },
        { name: 'value4_desc', type: 'string', title: 'Value 4 Description' },
        { name: 'cta_primary', type: 'string', title: 'Primary CTA' },
        { name: 'cta_secondary', type: 'string', title: 'Secondary CTA' },
        { name: 'note', type: 'string', title: 'Note' },
      ],
    },
  ],
};
