export default {
  name: 'pricing',
  title: 'Pricing Section',
  type: 'document',
  fields: [
    {
      name: 'nl',
      title: '🇳🇱 Dutch (Nederlands)',
      type: 'object',
      fields: [
        { name: 'title', type: 'string', title: 'Title' },
        { name: 'subtitle', type: 'text', title: 'Subtitle' },
        { name: 'tier1_name', type: 'string', title: 'Tier 1 Name' },
        { name: 'tier1_price', type: 'string', title: 'Tier 1 Price' },
        { name: 'tier1_desc', type: 'text', title: 'Tier 1 Description' },
        { name: 'tier1_feature1', type: 'string', title: 'Tier 1 Feature 1' },
        { name: 'tier1_feature2', type: 'string', title: 'Tier 1 Feature 2' },
        { name: 'tier1_feature3', type: 'string', title: 'Tier 1 Feature 3' },
        { name: 'tier1_cta', type: 'string', title: 'Tier 1 CTA' },
        { name: 'tier2_name', type: 'string', title: 'Tier 2 Name' },
        { name: 'tier2_price', type: 'string', title: 'Tier 2 Price' },
        { name: 'tier2_desc', type: 'text', title: 'Tier 2 Description' },
        { name: 'tier2_feature1', type: 'string', title: 'Tier 2 Feature 1' },
        { name: 'tier2_feature2', type: 'string', title: 'Tier 2 Feature 2' },
        { name: 'tier2_feature3', type: 'string', title: 'Tier 2 Feature 3' },
        { name: 'tier2_cta', type: 'string', title: 'Tier 2 CTA' },
        { name: 'tier3_name', type: 'string', title: 'Tier 3 Name' },
        { name: 'tier3_price', type: 'string', title: 'Tier 3 Price' },
        { name: 'tier3_desc', type: 'text', title: 'Tier 3 Description' },
        { name: 'tier3_feature1', type: 'string', title: 'Tier 3 Feature 1' },
        { name: 'tier3_feature2', type: 'string', title: 'Tier 3 Feature 2' },
        { name: 'tier3_feature3', type: 'string', title: 'Tier 3 Feature 3' },
        { name: 'tier3_cta', type: 'string', title: 'Tier 3 CTA' },
      ],
    },
    {
      name: 'en',
      title: '🇬🇧 English',
      type: 'object',
      fields: [
        { name: 'title', type: 'string', title: 'Title' },
        { name: 'subtitle', type: 'text', title: 'Subtitle' },
        { name: 'tier1_name', type: 'string', title: 'Tier 1 Name' },
        { name: 'tier1_price', type: 'string', title: 'Tier 1 Price' },
        { name: 'tier1_desc', type: 'text', title: 'Tier 1 Description' },
        { name: 'tier1_feature1', type: 'string', title: 'Tier 1 Feature 1' },
        { name: 'tier1_feature2', type: 'string', title: 'Tier 1 Feature 2' },
        { name: 'tier1_feature3', type: 'string', title: 'Tier 1 Feature 3' },
        { name: 'tier1_cta', type: 'string', title: 'Tier 1 CTA' },
        { name: 'tier2_name', type: 'string', title: 'Tier 2 Name' },
        { name: 'tier2_price', type: 'string', title: 'Tier 2 Price' },
        { name: 'tier2_desc', type: 'text', title: 'Tier 2 Description' },
        { name: 'tier2_feature1', type: 'string', title: 'Tier 2 Feature 1' },
        { name: 'tier2_feature2', type: 'string', title: 'Tier 2 Feature 2' },
        { name: 'tier2_feature3', type: 'string', title: 'Tier 2 Feature 3' },
        { name: 'tier2_cta', type: 'string', title: 'Tier 2 CTA' },
        { name: 'tier3_name', type: 'string', title: 'Tier 3 Name' },
        { name: 'tier3_price', type: 'string', title: 'Tier 3 Price' },
        { name: 'tier3_desc', type: 'text', title: 'Tier 3 Description' },
        { name: 'tier3_feature1', type: 'string', title: 'Tier 3 Feature 1' },
        { name: 'tier3_feature2', type: 'string', title: 'Tier 3 Feature 2' },
        { name: 'tier3_feature3', type: 'string', title: 'Tier 3 Feature 3' },
        { name: 'tier3_cta', type: 'string', title: 'Tier 3 CTA' },
      ],
    },
  ],
};
