export default {
  name: 'services',
  title: 'Services Section',
  type: 'document',
  fields: [
    {
      name: 'nl',
      title: '🇳🇱 Dutch (Nederlands)',
      type: 'object',
      fields: [
        { name: 'title', type: 'string', title: 'Title' },
        { name: 'subtitle', type: 'text', title: 'Subtitle' },
        { name: '1_title', type: 'string', title: 'Service 1 Title' },
        { name: '1_desc', type: 'text', title: 'Service 1 Description' },
        { name: '1_outcome', type: 'text', title: 'Service 1 Outcome' },
        { name: '2_title', type: 'string', title: 'Service 2 Title' },
        { name: '2_desc', type: 'text', title: 'Service 2 Description' },
        { name: '2_outcome', type: 'text', title: 'Service 2 Outcome' },
        { name: '3_title', type: 'string', title: 'Service 3 Title' },
        { name: '3_desc', type: 'text', title: 'Service 3 Description' },
        { name: '3_outcome', type: 'text', title: 'Service 3 Outcome' },
        { name: '4_title', type: 'string', title: 'Service 4 Title' },
        { name: '4_desc', type: 'text', title: 'Service 4 Description' },
        { name: '4_outcome', type: 'text', title: 'Service 4 Outcome' },
        { name: '5_title', type: 'string', title: 'Service 5 Title' },
        { name: '5_desc', type: 'text', title: 'Service 5 Description' },
        { name: '5_outcome', type: 'text', title: 'Service 5 Outcome' },
        { name: '6_title', type: 'string', title: 'Service 6 Title' },
        { name: '6_desc', type: 'text', title: 'Service 6 Description' },
        { name: '6_outcome', type: 'text', title: 'Service 6 Outcome' },
      ],
    },
    {
      name: 'en',
      title: '🇬🇧 English',
      type: 'object',
      fields: [
        { name: 'title', type: 'string', title: 'Title' },
        { name: 'subtitle', type: 'text', title: 'Subtitle' },
        { name: '1_title', type: 'string', title: 'Service 1 Title' },
        { name: '1_desc', type: 'text', title: 'Service 1 Description' },
        { name: '1_outcome', type: 'text', title: 'Service 1 Outcome' },
        { name: '2_title', type: 'string', title: 'Service 2 Title' },
        { name: '2_desc', type: 'text', title: 'Service 2 Description' },
        { name: '2_outcome', type: 'text', title: 'Service 2 Outcome' },
        { name: '3_title', type: 'string', title: 'Service 3 Title' },
        { name: '3_desc', type: 'text', title: 'Service 3 Description' },
        { name: '3_outcome', type: 'text', title: 'Service 3 Outcome' },
        { name: '4_title', type: 'string', title: 'Service 4 Title' },
        { name: '4_desc', type: 'text', title: 'Service 4 Description' },
        { name: '4_outcome', type: 'text', title: 'Service 4 Outcome' },
        { name: '5_title', type: 'string', title: 'Service 5 Title' },
        { name: '5_desc', type: 'text', title: 'Service 5 Description' },
        { name: '5_outcome', type: 'text', title: 'Service 5 Outcome' },
        { name: '6_title', type: 'string', title: 'Service 6 Title' },
        { name: '6_desc', type: 'text', title: 'Service 6 Description' },
        { name: '6_outcome', type: 'text', title: 'Service 6 Outcome' },
      ],
    },
  ],
};
